app/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("", include("quotes.urls")),
    path("authors/", include("authors.urls")),
    path("users/", include("users.urls")),
    path("admin/", admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

authors/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from . import views

app_name = 'authors'

urlpatterns = [
    path('author/<int:pk>', views.AuthorPageView.as_view(), name='details'),
    path('create/', login_required(views.CreateAuthorView.as_view()), name='create.author')
]

quotes/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from . import views

app_name = 'quotes'

urlpatterns = [
    path('', views.MainPageView.as_view(), name='main'),
    path('tag/<int:pk>', views.TagPageView.as_view(), name='tag'),
    path('quote/create', login_required(views.CreateQuoteView.as_view()), name='create.quote')
]

users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('login/', views.LoginPageView.as_view(), name='login'),
    path('registration/', views.RegistrationPageView.as_view(), name='registration'),
    path('logout/', views.logoutuser, name='logout')
]

authors/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class Author(models.Model):
    fullname = models.CharField(max_length=50, null=False)
    born_date = models.DateField(null=False)
    born_location = models.CharField(max_length=100, null=False)
    description = models.TextField(null=False)
    user = models.ForeignKey(User, on_delete=models.CASCADE, default=1)

    def __str__(self):
        return f"{self.fullname}"

quotes/models.py
from django.db import models
from authors.models import Author
from django.contrib.auth.models import User


# Create your models here.
class Tag(models.Model):
    name = models.CharField(max_length=50, null=False, unique=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, default=1)

    class Meta:
        constraints = [
            models.UniqueConstraint(fields=['user', 'name'], name='tag_of_user')
        ]

    def __str__(self):
        return f"{self.name}"


class Quote(models.Model):
    quote = models.CharField(null=False)
    tags = models.ManyToManyField(Tag)
    author = models.ForeignKey(Author, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE, default=1)

    def __str__(self):
        return f"{self.quote}"

users/models.py
from django.db import models

# Create your models here.

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User


class LoginForm(AuthenticationForm):
    class Meta:
        model = User
        fields = ['username', 'password']


class RegistrationForm(UserCreationForm):
    username = forms.CharField(max_length=100,
                               required=True,
                               widget=forms.TextInput())

    password1 = forms.CharField(max_length=50,
                                required=True,
                                widget=forms.PasswordInput())

    password2 = forms.CharField(max_length=50,
                                required=True,
                                widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ['username', 'password1', 'password2']

authors/views.py
from django import forms
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView
from django.shortcuts import redirect
from .models import Author


# Create your views here.
class AuthorPageView(DetailView):
    template_name = 'authors/author-details.html'
    model = Author
    context_object_name = 'author'


class CreateAuthorView(CreateView):
    model = Author
    fields = ['fullname', 'born_date', 'born_location', 'description']
    template_name = 'authors/author-create-form.html'

    def get_form(self, form_class=None):
        form = super(CreateAuthorView, self).get_form(form_class)
        form.fields['born_date'].widget = forms.DateInput(attrs={
                'type': 'date', 'placeholder': 'yyyy-mm-dd (DOB)',
                'class': 'form-control'
                })
        return form

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.user = self.request.user
        self.object.save()
        return redirect(to='authors:create.author')

quotes/views.py
from django.views.generic import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView
from django.db.models import Count
from django.shortcuts import redirect
from .models import Quote, Tag


# Create your views here.
class MainPageView(ListView):
    template_name = 'quotes/index.html'
    context_object_name = 'quotes_list'
    model = Quote
    paginate_by = 10
    top_tags_count = 10

    def get_context_data(self, *args, **kwargs):
        context = super(MainPageView, self).get_context_data(*args, **kwargs)
        context['top_tags'] = Tag.objects.annotate(num_quotes=Count('quote')).order_by('-num_quotes')[:10]
        return context


class TagPageView(DetailView):
    template_name = 'quotes/tag.html'
    model = Tag
    context_object_name = 'tag'


class CreateQuoteView(CreateView):
    model = Quote
    fields = ['quote', 'tags', 'author']
    template_name = 'quotes/quote_create_form.html'

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.user = self.request.user
        self.object.save()
        return redirect(to='quotes:create.quote')

users/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.views import View
from django.http import HttpRequest
from braces.views import AnonymousRequiredMixin
from .forms import LoginForm, RegistrationForm


# Create your views here.
class LoginPageView(AnonymousRequiredMixin, View):
    template_name = "users/login.html"

    def get(self, request: HttpRequest):
        return render(request, self.template_name, {'form': LoginForm()})

    def post(self, request: HttpRequest):
        user = authenticate(username=request.POST['username'], password=request.POST['password'])
        if user is None:
            messages.error(request, 'Username or password didn\'t match')
            return redirect(to='users:login')

        login(request, user)
        return redirect(to='quotes:main')


class RegistrationPageView(AnonymousRequiredMixin, View):
    template_name = "users/registration.html"

    def get(self, request: HttpRequest):
        return render(request, self.template_name, {'form': RegistrationForm})

    def post(self, request: HttpRequest):
        form = RegistrationForm(request.POST)
        if form.is_valid():
            form.save()
            user = authenticate(username=request.POST['username'], password=request.POST['password1'])
            login(request, user)
            return redirect(to='quotes:main')
        else:
            return render(request, 'users/registration.html', {'form': form})


@login_required
def logoutuser(request):
    logout(request)
    return redirect(to='quotes:main')

app/templates/app/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8"/>
    <title>Quotes</title>
    <link rel="stylesheet" href="https://unpkg.com/@picocss/pico@latest/css/pico.min.css"/>
</head>
<body>
<main class="container">
    <h1>Main page</h1>
</main>
</body>
</html>

authors/templates/authors/author-create-form.html
{% extends "quotes/base.html" %}

{% block content %}
    <form method="post">{% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Save">
    </form>
{% endblock content %}

authors/templates/authors/author-details.html
{% extends "quotes/base.html" %}

{% block content %}
    <h1>{{ author.fullname }}</h1>
    <div>
        <b>Born: </b><span>{{ author.born_date }} {{ author.born_location }}</span>
    </div>
    <div>
        <b>Description:</b>
        <p>{{ author.description }}</p>
    </div>
{% endblock content %}

quotes/templates/quotes/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8"/>
    <title>Quotes - Homework 10</title>
    <link rel="stylesheet" href="https://unpkg.com/@picocss/pico@latest/css/pico.min.css" />
    {% load static %}
    <link rel="stylesheet" href="{% static 'quotes/style.css' %}">
</head>
<body>
<main class="container">
    <nav style="margin-bottom: 10px; border-bottom: 2px solid; padding-left: 30px; padding-right: 10px">
        <ul>
            <li><a href="/" role="button">Quotes app</a></li>
        </ul>
        {% if user.is_authenticated %}
            <ul>
                <li>Welcome <b>{{ user.username }}!</b></li>
                <li><a href="{% url 'quotes:create.quote' %}" role="button">Add quote</a></li>
                <li><a href="{% url 'authors:create.author' %}" role="button">Add author</a></li>
                <li><a href="{% url 'users:logout' %}" role="button">Logout</a></li>
            </ul>
        {% else %}
            <ul>
                <li><a href="{% url 'users:login' %}" role="button">Login</a></li>
                <li><a href="{% url 'users:registration' %}" role="button">Registration</a></li>
            </ul>
        {% endif %}
    </nav>
    {% block content %} {% endblock %}
</main>
</body>
</html>

quotes/templates/quotes/components/quote.html
<blockquote style="margin-bottom: 20px; border: 1px solid; padding-left: 30px; padding-right: 30px">
    {{quote.quote}}
    <footer>
        <cite>
            by <small>{{quote.author.fullname}}</small>
            <a href="{% url 'authors:details' quote.author.id %}">(about)</a>
        </cite>
        <div>
            {% for tag in quote.tags.all %}
            <a class="contrast" href="{% url 'quotes:tag' tag.id %}">{{tag.name}}</a>
            {% endfor %}
        </div>
    </footer>
</blockquote>

quotes/templates/quotes/index.html
{% extends "quotes/base.html" %}

{% block content %}
    <div class="main-page">
        <div class="main-page--quotes">
            {% for quote in quotes_list %}
                {% include "quotes/components/quote.html" with quote=quote %}
            {% endfor %}

            <div class="pagination">
                <span class="step-links">
                    {% if page_obj.has_previous %}
                        <a href="?page=1">&laquo; first</a>
                        <span>&nbsp;&nbsp;</span>
                        <a href="?page={{ page_obj.previous_page_number }}">previous</a>
                        <span>&nbsp;&nbsp;</span>
                    {% endif %}

                    <span class="current">
                        Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
                    </span>

                    {% if page_obj.has_next %}
                        <span>&nbsp;&nbsp;</span>
                        <a href="?page={{ page_obj.next_page_number }}">next</a>
                        <span>&nbsp;&nbsp;</span>
                        <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
                    {% endif %}
                </span>
            </div>
        </div>
        <span style="margin-top: 10px; padding-top: 10px">
            <div class="main-page--top-tags">
                <h3>&nbsp;&nbsp;&nbsp;&nbsp;Top 10 tags</h3>
                {% for tag in top_tags %}
                <span>&nbsp;&nbsp;&nbsp;</span>
                <span>&nbsp;&nbsp;&nbsp;</span>
                    <span style="padding-bottom: 4px; padding-left: 16px; border-left: 2px solid">
                        <a class="contrast" href="{% url 'quotes:tag' tag.id %}">{{tag.name}}</a><br>
                    </span>
                    {% endfor %}
            </div>
        </span>
    </div>
{% endblock content %}

quotes/templates/quotes/quote_create_form.html
{% extends "quotes/base.html" %}

{% block content %}
    <form method="post">{% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Save">
    </form>
{% endblock content %}

quotes/templates/quotes/tag.html
{% extends "quotes/base.html" %}

{% block content %}
    <h1>{{ tag.name }}</h1>
    <div>
        {% for quote in tag.quote_set.all %}
            {% include "quotes/components/quote.html" with quote=quote %}
        {% endfor %}
    </div>
{% endblock content %}

users/templates/users/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8"/>
    <title>Quotes</title>
    {% comment %} <link rel="stylesheet" href="https://unpkg.com/@picocss/pico@latest/css/pico.min.css"/> {% endcomment %}
    <link rel="stylesheet" href="/css/pico.min.css" />

</head>
<body>
<main class="container">
    <h1>Users</h1>
</main>
</body>
</html>

users/templates/users/login.html
{% extends "quotes/base.html" %}

{% block content %}

    {% if messages %}
    <div>
        {% for message in messages %}
        <div {% if message.tags %} class="alert-{{ message.tags }}" {% endif %}>{{ message }}</div>
        {% endfor %}
    </div>
    {% endif %}

    <form action="{% url 'users:login' %}" method="post">
        {% csrf_token %}
        <div>
            <label> Username:
                {{ form.username }}
            </label>
        </div>

        <div>
            <label>Password:
                {{ form.password }}
            </label>
        </div>

        <div class="grid">
            <button type="submit">Submit</button>
            <button type="reset" class="secondary">Reset</button>
        </div>
    </form>


{% endblock content %}

users/templates/users/registration.html
{% extends "quotes/base.html" %}

{% block content %}

 <div>
        <h2>Sign Up</h2>
    </div>

    <form method="post" action="{% url 'users:registration' %}">
        {% csrf_token %}
        <div>
            <label> Username:
                {{ form.username }}
            </label>
            <span>{{ form.errors.username }}</span>
        </div>
        <br>
        <div>
            <label> Password:
                {{ form.password1 }}
            </label>
            <span>{{ form.errors.password1 }}</span>
        </div>
        <div>
            <label> Password confirmation:
                {{ form.password2 }}
            </label>
            <span>{{ form.errors.password2 }}</span>
        </div>
        <div class="grid">
            <button type="submit">Submit</button>
            <button type="reset" class="secondary">Reset</button>
        </div>
    </form>

{% endblock content %}